// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HandshakeRequest is sent once, immediately after the agent connects to a
// freshly launched plugin process.
type HandshakeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Highest plugin protocol version the calling agent supports.
	ProtocolVersion uint32 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

// HandshakeResponse carries the plugin's manifest, as introduced in the
// vision document (section 8.3).
type HandshakeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol version the plugin will speak for the rest of this session.
	// Must not exceed HandshakeRequest.protocol_version; the agent rejects the
	// plugin if it does.
	ProtocolVersion uint32         `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	PluginId        string         `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	PluginVersion   string         `protobuf:"bytes,3,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	Contributes     *Contributions `protobuf:"bytes,4,opt,name=contributes,proto3" json:"contributes,omitempty"`
	Permissions     []string       `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HandshakeResponse) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *HandshakeResponse) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *HandshakeResponse) GetContributes() *Contributions {
	if x != nil {
		return x.Contributes
	}
	return nil
}

func (x *HandshakeResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// Contributions lists the identifiers a plugin adds to the agent's
// registries once installed. Every entry is a stable, versioned identifier
// such as "postgresql.query@1".
type Contributions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connectors    []string               `protobuf:"bytes,1,rep,name=connectors,proto3" json:"connectors,omitempty"`
	Actions       []string               `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contributions) Reset() {
	*x = Contributions{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contributions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contributions) ProtoMessage() {}

func (x *Contributions) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contributions.ProtoReflect.Descriptor instead.
func (*Contributions) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Contributions) GetConnectors() []string {
	if x != nil {
		return x.Connectors
	}
	return nil
}

func (x *Contributions) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

var File_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x16plugin/v1/plugin.proto\x12\tplugin.v1\"=\n" +
	"\x10HandshakeRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\"\xe0\x01\n" +
	"\x11HandshakeResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\tR\bpluginId\x12%\n" +
	"\x0eplugin_version\x18\x03 \x01(\tR\rpluginVersion\x12:\n" +
	"\vcontributes\x18\x04 \x01(\v2\x18.plugin.v1.ContributionsR\vcontributes\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissions\"I\n" +
	"\rContributions\x12\x1e\n" +
	"\n" +
	"connectors\x18\x01 \x03(\tR\n" +
	"connectors\x12\x18\n" +
	"\aactions\x18\x02 \x03(\tR\aactions2W\n" +
	"\rPluginService\x12F\n" +
	"\tHandshake\x12\x1b.plugin.v1.HandshakeRequest\x1a\x1c.plugin.v1.HandshakeResponseB7Z5github.com/lucasglmt/patchcord/api/plugin/v1;pluginv1b\x06proto3"

var (
	file_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_plugin_v1_plugin_proto_rawDescData []byte
)

func file_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_plugin_proto_rawDesc), len(file_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_plugin_v1_plugin_proto_rawDescData
}

var file_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_plugin_v1_plugin_proto_goTypes = []any{
	(*HandshakeRequest)(nil),  // 0: plugin.v1.HandshakeRequest
	(*HandshakeResponse)(nil), // 1: plugin.v1.HandshakeResponse
	(*Contributions)(nil),     // 2: plugin.v1.Contributions
}
var file_plugin_v1_plugin_proto_depIdxs = []int32{
	2, // 0: plugin.v1.HandshakeResponse.contributes:type_name -> plugin.v1.Contributions
	0, // 1: plugin.v1.PluginService.Handshake:input_type -> plugin.v1.HandshakeRequest
	1, // 2: plugin.v1.PluginService.Handshake:output_type -> plugin.v1.HandshakeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_plugin_v1_plugin_proto_init() }
func file_plugin_v1_plugin_proto_init() {
	if File_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_plugin_proto_rawDesc), len(file_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_v1_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_plugin_v1_plugin_proto = out.File
	file_plugin_v1_plugin_proto_goTypes = nil
	file_plugin_v1_plugin_proto_depIdxs = nil
}
