// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HandshakeRequest is sent once, immediately after the agent connects to a
// freshly launched plugin process.
type HandshakeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Highest plugin protocol version the calling agent supports.
	ProtocolVersion uint32 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

// HandshakeResponse carries the plugin's manifest, as introduced in the
// vision document (section 8.3).
type HandshakeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol version the plugin will speak for the rest of this session.
	// Must not exceed HandshakeRequest.protocol_version; the agent rejects the
	// plugin if it does.
	ProtocolVersion uint32         `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	PluginId        string         `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	PluginVersion   string         `protobuf:"bytes,3,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	Contributes     *Contributions `protobuf:"bytes,4,opt,name=contributes,proto3" json:"contributes,omitempty"`
	Permissions     []string       `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HandshakeResponse) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *HandshakeResponse) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *HandshakeResponse) GetContributes() *Contributions {
	if x != nil {
		return x.Contributes
	}
	return nil
}

func (x *HandshakeResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// Contributions lists the identifiers a plugin adds to the agent's
// registries once installed. Every entry is a stable, versioned identifier
// such as "postgresql.query@1".
type Contributions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connectors    []string               `protobuf:"bytes,1,rep,name=connectors,proto3" json:"connectors,omitempty"`
	Actions       []string               `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contributions) Reset() {
	*x = Contributions{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contributions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contributions) ProtoMessage() {}

func (x *Contributions) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contributions.ProtoReflect.Descriptor instead.
func (*Contributions) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Contributions) GetConnectors() []string {
	if x != nil {
		return x.Connectors
	}
	return nil
}

func (x *Contributions) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

// ExecuteActionRequest asks the plugin to run one action.
type ExecuteActionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The action identifier, e.g. "text.uppercase@1".
	Action string           `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Input  *structpb.Struct `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	// The resolved configuration and secrets of the connector the calling
	// workflow step bound to this action, if any. Absent when the step bound
	// no connector. Never persisted by the agent — assembled fresh for this
	// one call.
	Connector     *ConnectorConfig `protobuf:"bytes,3,opt,name=connector,proto3" json:"connector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteActionRequest) Reset() {
	*x = ExecuteActionRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteActionRequest) ProtoMessage() {}

func (x *ExecuteActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteActionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteActionRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ExecuteActionRequest) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ExecuteActionRequest) GetConnector() *ConnectorConfig {
	if x != nil {
		return x.Connector
	}
	return nil
}

// ConnectorConfig carries one connector's resolved configuration and secret
// values, ready for a plugin to use for the duration of one action call.
type ConnectorConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Secrets       *structpb.Struct       `protobuf:"bytes,3,opt,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectorConfig) Reset() {
	*x = ConnectorConfig{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorConfig) ProtoMessage() {}

func (x *ConnectorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorConfig.ProtoReflect.Descriptor instead.
func (*ConnectorConfig) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectorConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConnectorConfig) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ConnectorConfig) GetSecrets() *structpb.Struct {
	if x != nil {
		return x.Secrets
	}
	return nil
}

// ExecuteActionResponse carries the action's output.
type ExecuteActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        *structpb.Struct       `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteActionResponse) Reset() {
	*x = ExecuteActionResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteActionResponse) ProtoMessage() {}

func (x *ExecuteActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteActionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteActionResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteActionResponse) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

// TestConnectorRequest asks the plugin to attempt a connection using one
// connector's resolved configuration and secrets.
type TestConnectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connector     *ConnectorConfig       `protobuf:"bytes,1,opt,name=connector,proto3" json:"connector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConnectorRequest) Reset() {
	*x = TestConnectorRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectorRequest) ProtoMessage() {}

func (x *TestConnectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectorRequest.ProtoReflect.Descriptor instead.
func (*TestConnectorRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *TestConnectorRequest) GetConnector() *ConnectorConfig {
	if x != nil {
		return x.Connector
	}
	return nil
}

// TestConnectorResponse reports the outcome of a connector test. A failed
// attempt (Ok = false) is a legitimate result, not an RPC error — the same
// distinction ExecuteActionResponse's callers already make between a
// business-level failure and a transport-level one.
type TestConnectorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// Human-readable detail: the error message on failure, or empty/a short
	// confirmation on success.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConnectorResponse) Reset() {
	*x = TestConnectorResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectorResponse) ProtoMessage() {}

func (x *TestConnectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectorResponse.ProtoReflect.Descriptor instead.
func (*TestConnectorResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *TestConnectorResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TestConnectorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x16plugin/v1/plugin.proto\x12\tplugin.v1\x1a\x1cgoogle/protobuf/struct.proto\"=\n" +
	"\x10HandshakeRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\"\xe0\x01\n" +
	"\x11HandshakeResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\tR\bpluginId\x12%\n" +
	"\x0eplugin_version\x18\x03 \x01(\tR\rpluginVersion\x12:\n" +
	"\vcontributes\x18\x04 \x01(\v2\x18.plugin.v1.ContributionsR\vcontributes\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissions\"I\n" +
	"\rContributions\x12\x1e\n" +
	"\n" +
	"connectors\x18\x01 \x03(\tR\n" +
	"connectors\x12\x18\n" +
	"\aactions\x18\x02 \x03(\tR\aactions\"\x97\x01\n" +
	"\x14ExecuteActionRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12-\n" +
	"\x05input\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05input\x128\n" +
	"\tconnector\x18\x03 \x01(\v2\x1a.plugin.v1.ConnectorConfigR\tconnector\"\x89\x01\n" +
	"\x0fConnectorConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06config\x121\n" +
	"\asecrets\x18\x03 \x01(\v2\x17.google.protobuf.StructR\asecrets\"H\n" +
	"\x15ExecuteActionResponse\x12/\n" +
	"\x06output\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06output\"P\n" +
	"\x14TestConnectorRequest\x128\n" +
	"\tconnector\x18\x01 \x01(\v2\x1a.plugin.v1.ConnectorConfigR\tconnector\"A\n" +
	"\x15TestConnectorResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xff\x01\n" +
	"\rPluginService\x12F\n" +
	"\tHandshake\x12\x1b.plugin.v1.HandshakeRequest\x1a\x1c.plugin.v1.HandshakeResponse\x12R\n" +
	"\rExecuteAction\x12\x1f.plugin.v1.ExecuteActionRequest\x1a .plugin.v1.ExecuteActionResponse\x12R\n" +
	"\rTestConnector\x12\x1f.plugin.v1.TestConnectorRequest\x1a .plugin.v1.TestConnectorResponseB7Z5github.com/lucasglmt/patchcord/api/plugin/v1;pluginv1b\x06proto3"

var (
	file_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_plugin_v1_plugin_proto_rawDescData []byte
)

func file_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_plugin_proto_rawDesc), len(file_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_plugin_v1_plugin_proto_rawDescData
}

var file_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_plugin_v1_plugin_proto_goTypes = []any{
	(*HandshakeRequest)(nil),      // 0: plugin.v1.HandshakeRequest
	(*HandshakeResponse)(nil),     // 1: plugin.v1.HandshakeResponse
	(*Contributions)(nil),         // 2: plugin.v1.Contributions
	(*ExecuteActionRequest)(nil),  // 3: plugin.v1.ExecuteActionRequest
	(*ConnectorConfig)(nil),       // 4: plugin.v1.ConnectorConfig
	(*ExecuteActionResponse)(nil), // 5: plugin.v1.ExecuteActionResponse
	(*TestConnectorRequest)(nil),  // 6: plugin.v1.TestConnectorRequest
	(*TestConnectorResponse)(nil), // 7: plugin.v1.TestConnectorResponse
	(*structpb.Struct)(nil),       // 8: google.protobuf.Struct
}
var file_plugin_v1_plugin_proto_depIdxs = []int32{
	2,  // 0: plugin.v1.HandshakeResponse.contributes:type_name -> plugin.v1.Contributions
	8,  // 1: plugin.v1.ExecuteActionRequest.input:type_name -> google.protobuf.Struct
	4,  // 2: plugin.v1.ExecuteActionRequest.connector:type_name -> plugin.v1.ConnectorConfig
	8,  // 3: plugin.v1.ConnectorConfig.config:type_name -> google.protobuf.Struct
	8,  // 4: plugin.v1.ConnectorConfig.secrets:type_name -> google.protobuf.Struct
	8,  // 5: plugin.v1.ExecuteActionResponse.output:type_name -> google.protobuf.Struct
	4,  // 6: plugin.v1.TestConnectorRequest.connector:type_name -> plugin.v1.ConnectorConfig
	0,  // 7: plugin.v1.PluginService.Handshake:input_type -> plugin.v1.HandshakeRequest
	3,  // 8: plugin.v1.PluginService.ExecuteAction:input_type -> plugin.v1.ExecuteActionRequest
	6,  // 9: plugin.v1.PluginService.TestConnector:input_type -> plugin.v1.TestConnectorRequest
	1,  // 10: plugin.v1.PluginService.Handshake:output_type -> plugin.v1.HandshakeResponse
	5,  // 11: plugin.v1.PluginService.ExecuteAction:output_type -> plugin.v1.ExecuteActionResponse
	7,  // 12: plugin.v1.PluginService.TestConnector:output_type -> plugin.v1.TestConnectorResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_plugin_v1_plugin_proto_init() }
func file_plugin_v1_plugin_proto_init() {
	if File_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_plugin_proto_rawDesc), len(file_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_v1_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_plugin_v1_plugin_proto = out.File
	file_plugin_v1_plugin_proto_goTypes = nil
	file_plugin_v1_plugin_proto_depIdxs = nil
}
