package workflow

import (
	"errors"
	"fmt"
	"os"
)

// ScaffoldTemplateMinimal and ScaffoldTemplateForeach are the values
// accepted by `workflow new --template` (internal/cli/workflow.go).
const (
	ScaffoldTemplateMinimal = "minimal"
	ScaffoldTemplateForeach = "foreach"
)

// scaffoldTemplate is hand-written rather than produced via yaml.Marshal(a
// Definition) so it can carry an explanatory header comment — something
// struct marshaling can't do. It references text.uppercase@1 (the
// reference plugin, plugins/examples/text) rather than a placeholder that
// would always fail validation: text.uppercase@1 is one of Patchcord's
// bundled reference plugins, auto-installed into any --data-dir the first
// time it's touched (ADR-0059), so `workflow validate`/`run` succeed on a
// fresh scaffold immediately, with nothing to install first.
const scaffoldTemplate = `# Generated by ` + "`patchcord workflow new`" + `. Replace the step below with
# your own action — text.uppercase@1 is one of Patchcord's bundled
# reference plugins, so this scaffold runs as-is with nothing to install.
schema_version: 1

id: %s
version: %d

trigger:
  type: manual

steps:
  - id: step
    uses: text.uppercase@1
    with:
      value: "hello"
`

// scaffoldForeachTemplate demonstrates Step.Foreach (ADR-0032): one action
// invocation per item of a literal list, with the current item available
// to `with` as ${{ each }}. It uses a literal list rather than a prior
// step's output so it validates and runs with only the same reference
// plugin scaffoldTemplate already depends on — no plugin whose output
// happens to be a list is required.
const scaffoldForeachTemplate = `# Generated by ` + "`patchcord workflow new --template foreach`" + `. Demonstrates
# a foreach step: one action invocation per item of a list, with the
# current item available to ` + "`with`" + ` as ${{ each }} (ADR-0032). Replace the
# list and the step's own action with your own.
schema_version: 1

id: %s
version: %d

trigger:
  type: manual

steps:
  - id: step
    uses: text.uppercase@1
    foreach: ["hello", "world"]
    with:
      value: "${{ each }}"
`

// Scaffold writes a minimal, valid workflow definition to path — equivalent
// to ScaffoldTemplate(path, id, version, ScaffoldTemplateMinimal). Kept as
// its own function since it is the one every other package's own
// scaffolding delegates to for a bundle's/plugin example's default
// embedded workflow (internal/bundles/scaffold.go): those always want the
// minimal template, never a caller-chosen one.
func Scaffold(path, id string, version int) error {
	return ScaffoldTemplate(path, id, version, ScaffoldTemplateMinimal)
}

// ScaffoldTemplate writes a valid workflow definition to path: id, version,
// a manual trigger, and one step demonstrating template — one of
// ScaffoldTemplateMinimal or ScaffoldTemplateForeach. A workflow must
// declare at least one step (Validate, "workflow must declare at least one
// step"), so neither skeleton can be empty. It returns an error if path
// already exists — ScaffoldTemplate never overwrites — or if template is
// none of the above.
func ScaffoldTemplate(path, id string, version int, template string) error {
	var raw string
	switch template {
	case ScaffoldTemplateMinimal:
		raw = scaffoldTemplate
	case ScaffoldTemplateForeach:
		raw = scaffoldForeachTemplate
	default:
		return fmt.Errorf("unknown workflow template %q (want %q or %q)", template, ScaffoldTemplateMinimal, ScaffoldTemplateForeach)
	}

	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("%q already exists", path)
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("check %q: %w", path, err)
	}

	content := fmt.Sprintf(raw, id, version)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %q: %w", path, err)
	}

	return nil
}
