package workflow

import (
	"errors"
	"fmt"
	"os"
)

// scaffoldTemplate is hand-written rather than produced via yaml.Marshal(a
// Definition) so it can carry an explanatory header comment — something
// struct marshaling can't do. It references text.uppercase@1 (the
// reference plugin, plugins/examples/text) rather than a placeholder that
// would always fail validation: `workflow validate` on a fresh scaffold
// only fails if that one reference plugin isn't installed yet, and
// succeeds immediately once it is.
const scaffoldTemplate = `# Generated by ` + "`patchcord workflow new`" + `. Replace the step below with
# your own action, or install the reference plugin
# (` + "`patchcord plugin install bin/plugins/text`" + `) to run this as-is.
schema_version: 1

id: %s
version: %d

trigger:
  type: manual

steps:
  - id: step
    uses: text.uppercase@1
    with:
      value: "hello"
`

// Scaffold writes a minimal, valid workflow definition to path: id,
// version, a manual trigger, and one step. A workflow must declare at
// least one step (Validate, "workflow must declare at least one step"), so
// the skeleton can't be empty. It returns an error if path already exists
// — Scaffold never overwrites.
func Scaffold(path, id string, version int) error {
	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("%q already exists", path)
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("check %q: %w", path, err)
	}

	content := fmt.Sprintf(scaffoldTemplate, id, version)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %q: %w", path, err)
	}

	return nil
}
