// Package codegen generates typed source code from plugin action and
// connector descriptors (JSON Schema). First target language: TypeScript.
package codegen

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/lucasglmt/patchcord/internal/plugins"
)

// header is written at the top of every generated file.
const header = "// Code generated by patchcord dev codegen — DO NOT EDIT."

// GenerateTypeScript converts a CatalogEntry into a complete .ts file
// containing one namespace (PascalCase of the plugin id) with Input/Output
// interfaces for every action and a Config interface for every connector.
func GenerateTypeScript(entry *plugins.CatalogEntry) ([]byte, error) {
	var buf bytes.Buffer

	fmt.Fprintln(&buf, header)
	fmt.Fprintf(&buf, "// Plugin: %s v%s\n", entry.PluginID, entry.Version)

	ns := pluginNamespace(entry.PluginID)

	if len(entry.Actions) == 0 && len(entry.Connectors) == 0 {
		fmt.Fprintf(&buf, "\n// Plugin %q declares no actions or connectors.\n", entry.PluginID)
		return buf.Bytes(), nil
	}

	fmt.Fprintf(&buf, "\nexport namespace %s {\n", ns)

	for i, action := range entry.Actions {
		base := actionTypeName(action.ID, entry.PluginID)

		if action.Description != "" {
			fmt.Fprintf(&buf, "  /** %s */\n", action.Description)
		}
		writeInterface(&buf, base+"Input", action.InputSchema, "  ")
		fmt.Fprintln(&buf)
		writeInterface(&buf, base+"Output", action.OutputSchema, "  ")

		if i < len(entry.Actions)-1 || len(entry.Connectors) > 0 {
			fmt.Fprintln(&buf)
		}
	}

	for i, conn := range entry.Connectors {
		base := connectorTypeName(conn.Type, entry.PluginID)

		if conn.Description != "" {
			fmt.Fprintf(&buf, "  /** %s */\n", conn.Description)
		}
		writeInterface(&buf, base+"Config", conn.ConfigSchema, "  ")

		if i < len(entry.Connectors)-1 {
			fmt.Fprintln(&buf)
		}
	}

	fmt.Fprintln(&buf, "}")

	return buf.Bytes(), nil
}

// pluginNamespace converts a plugin id to a PascalCase namespace name.
// "text" → "Text", "google-calendar" → "GoogleCalendar".
func pluginNamespace(id string) string {
	return toPascalCase(id)
}

// actionTypeName strips the plugin id prefix and version suffix from an
// action id, then converts the remainder to PascalCase.
// actionTypeName("text.uppercase@1", "text") → "Uppercase".
func actionTypeName(actionID, pluginID string) string {
	name := actionID

	// Strip plugin prefix ("text.uppercase@1" → "uppercase@1").
	if strings.HasPrefix(name, pluginID+".") {
		name = name[len(pluginID)+1:]
	}

	// Strip version suffix ("uppercase@1" → "uppercase").
	if at := strings.LastIndex(name, "@"); at >= 0 {
		name = name[:at]
	}

	return toPascalCase(name)
}

// connectorTypeName strips the plugin id prefix and version suffix from a
// connector type, then converts the remainder to PascalCase.
// connectorTypeName("postgresql.connection@1", "postgresql") → "Connection".
func connectorTypeName(connType, pluginID string) string {
	name := connType

	if strings.HasPrefix(name, pluginID+".") {
		name = name[len(pluginID)+1:]
	}

	if at := strings.LastIndex(name, "@"); at >= 0 {
		name = name[:at]
	}

	return toPascalCase(name)
}

// toPascalCase splits on "-", "_", or "." and capitalises each segment.
func toPascalCase(s string) string {
	var b strings.Builder

	upper := true
	for _, r := range s {
		switch r {
		case '-', '_', '.':
			upper = true
		default:
			if upper {
				b.WriteString(strings.ToUpper(string(r)))
				upper = false
			} else {
				b.WriteRune(r)
			}
		}
	}

	return b.String()
}

// writeInterface writes a TypeScript export interface block from a JSON
// Schema object. If the schema is nil or empty, it writes an empty
// interface.
func writeInterface(buf *bytes.Buffer, name string, schema map[string]any, indent string) {
	fmt.Fprintf(buf, "%sexport interface %s {\n", indent, name)

	if schema == nil {
		fmt.Fprintf(buf, "%s}\n", indent)
		return
	}

	props, _ := schema["properties"].(map[string]any)
	required := requiredSet(schema)

	if props == nil {
		fmt.Fprintf(buf, "%s}\n", indent)
		return
	}

	// Sort property names for deterministic output.
	keys := sortedKeys(props)

	for _, key := range keys {
		propSchema, ok := props[key].(map[string]any)
		if !ok {
			continue
		}

		if desc, ok := propSchema["description"].(string); ok && desc != "" {
			fmt.Fprintf(buf, "%s  /** %s */\n", indent, desc)
		}

		opt := "?"
		if required[key] {
			opt = ""
		}

		tsType := schemaToTS(propSchema, indent+"  ")
		fmt.Fprintf(buf, "%s  %s%s: %s;\n", indent, key, opt, tsType)
	}

	fmt.Fprintf(buf, "%s}\n", indent)
}

// schemaToTS converts a single JSON Schema property definition to a
// TypeScript type expression.
func schemaToTS(schema map[string]any, indent string) string {
	// Enum takes priority — produce a union of literals.
	if enumVals, ok := schema["enum"].([]any); ok && len(enumVals) > 0 {
		return enumToTS(enumVals)
	}

	typ, _ := schema["type"].(string)

	switch typ {
	case "string":
		return "string"
	case "number", "integer":
		return "number"
	case "boolean":
		return "boolean"
	case "array":
		return arrayToTS(schema, indent)
	case "object":
		return objectToTS(schema, indent)
	default:
		return "unknown"
	}
}

// enumToTS converts a JSON Schema enum array to a TypeScript union of
// string literals. Non-string values are rendered via fmt.Sprintf.
func enumToTS(vals []any) string {
	parts := make([]string, len(vals))
	for i, v := range vals {
		switch v := v.(type) {
		case string:
			parts[i] = fmt.Sprintf("%q", v)
		default:
			parts[i] = fmt.Sprintf("%v", v)
		}
	}
	return strings.Join(parts, " | ")
}

// arrayToTS handles {"type":"array","items":{...}}.
func arrayToTS(schema map[string]any, indent string) string {
	items, ok := schema["items"].(map[string]any)
	if !ok {
		return "Array<unknown>"
	}

	inner := schemaToTS(items, indent)

	// Wrap union types in parens for clarity: Array<"a" | "b">.
	if strings.Contains(inner, "|") {
		return fmt.Sprintf("Array<%s>", inner)
	}

	return fmt.Sprintf("Array<%s>", inner)
}

// objectToTS handles inline {"type":"object","properties":{...}}.
func objectToTS(schema map[string]any, indent string) string {
	props, ok := schema["properties"].(map[string]any)
	if !ok {
		return "Record<string, unknown>"
	}

	required := requiredSet(schema)
	keys := sortedKeys(props)

	var buf bytes.Buffer
	buf.WriteString("{\n")

	for _, key := range keys {
		propSchema, ok := props[key].(map[string]any)
		if !ok {
			continue
		}

		if desc, ok := propSchema["description"].(string); ok && desc != "" {
			fmt.Fprintf(&buf, "%s  /** %s */\n", indent, desc)
		}

		opt := "?"
		if required[key] {
			opt = ""
		}

		tsType := schemaToTS(propSchema, indent+"  ")
		fmt.Fprintf(&buf, "%s  %s%s: %s;\n", indent, key, opt, tsType)
	}

	fmt.Fprintf(&buf, "%s}", indent)
	return buf.String()
}

// requiredSet returns the set of required property names from a JSON
// Schema object definition.
func requiredSet(schema map[string]any) map[string]bool {
	reqSlice, _ := schema["required"].([]any)
	m := make(map[string]bool, len(reqSlice))
	for _, v := range reqSlice {
		if s, ok := v.(string); ok {
			m[s] = true
		}
	}
	return m
}

// sortedKeys returns the keys of a map in sorted order.
func sortedKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
