package codegen

import (
	"strings"
	"testing"

	"github.com/lucasglmt/patchcord/internal/plugins"
)

func TestPluginNamespace(t *testing.T) {
	tests := []struct {
		id   string
		want string
	}{
		{"text", "Text"},
		{"google-calendar", "GoogleCalendar"},
		{"my.plugin", "MyPlugin"},
		{"a_b-c.d", "ABCD"},
	}
	for _, tt := range tests {
		t.Run(tt.id, func(t *testing.T) {
			got := pluginNamespace(tt.id)
			if got != tt.want {
				t.Errorf("pluginNamespace(%q) = %q, want %q", tt.id, got, tt.want)
			}
		})
	}
}

func TestActionTypeName(t *testing.T) {
	tests := []struct {
		actionID string
		pluginID string
		want     string
	}{
		{"text.uppercase@1", "text", "Uppercase"},
		{"text.to-lower@2", "text", "ToLower"},
		{"imap.fetch-messages@1", "imap", "FetchMessages"},
		{"noprefix@1", "other", "Noprefix"},
		{"bare", "bare", "Bare"},
	}
	for _, tt := range tests {
		t.Run(tt.actionID, func(t *testing.T) {
			got := actionTypeName(tt.actionID, tt.pluginID)
			if got != tt.want {
				t.Errorf("actionTypeName(%q, %q) = %q, want %q", tt.actionID, tt.pluginID, got, tt.want)
			}
		})
	}
}

func TestConnectorTypeName(t *testing.T) {
	tests := []struct {
		connType string
		pluginID string
		want     string
	}{
		{"postgresql.connection@1", "postgresql", "Connection"},
		{"imap.server-config@1", "imap", "ServerConfig"},
		{"bare", "bare", "Bare"},
	}
	for _, tt := range tests {
		t.Run(tt.connType, func(t *testing.T) {
			got := connectorTypeName(tt.connType, tt.pluginID)
			if got != tt.want {
				t.Errorf("connectorTypeName(%q, %q) = %q, want %q", tt.connType, tt.pluginID, got, tt.want)
			}
		})
	}
}

func TestSchemaToTS(t *testing.T) {
	tests := []struct {
		name   string
		schema map[string]any
		want   string
	}{
		{"string", map[string]any{"type": "string"}, "string"},
		{"number", map[string]any{"type": "number"}, "number"},
		{"integer", map[string]any{"type": "integer"}, "number"},
		{"boolean", map[string]any{"type": "boolean"}, "boolean"},
		{"no type", map[string]any{}, "unknown"},
		{"nil map", nil, "unknown"},
		{
			"enum",
			map[string]any{"enum": []any{"a", "b", "c"}},
			`"a" | "b" | "c"`,
		},
		{
			"array of strings",
			map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
			"Array<string>",
		},
		{
			"array without items",
			map[string]any{"type": "array"},
			"Array<unknown>",
		},
		{
			"object without properties",
			map[string]any{"type": "object"},
			"Record<string, unknown>",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			schema := tt.schema
			if schema == nil {
				schema = map[string]any{}
			}
			got := schemaToTS(schema, "")
			if got != tt.want {
				t.Errorf("schemaToTS() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestGenerateTypeScript_SimpleAction(t *testing.T) {
	entry := &plugins.CatalogEntry{
		PluginID: "text",
		Version:  "1.0.0",
		Actions: []plugins.ActionDescriptor{
			{
				ID:          "text.uppercase@1",
				Description: "Converts a string to upper case.",
				InputSchema: map[string]any{
					"type": "object",
					"properties": map[string]any{
						"value": map[string]any{
							"type":        "string",
							"description": "The string to convert.",
						},
					},
					"required": []any{"value"},
				},
				OutputSchema: map[string]any{
					"type": "object",
					"properties": map[string]any{
						"value": map[string]any{
							"type":        "string",
							"description": "value, converted to upper case.",
						},
					},
					"required": []any{"value"},
				},
			},
		},
	}

	out, err := GenerateTypeScript(entry)
	if err != nil {
		t.Fatalf("GenerateTypeScript() error: %v", err)
	}
	s := string(out)

	mustContain := []string{
		"// Code generated by patchcord dev codegen",
		"DO NOT EDIT",
		"// Plugin: text v1.0.0",
		"export namespace Text {",
		"/** Converts a string to upper case. */",
		"export interface UppercaseInput {",
		"/** The string to convert. */",
		"value: string;",
		"export interface UppercaseOutput {",
	}
	for _, want := range mustContain {
		if !strings.Contains(s, want) {
			t.Errorf("output missing %q\n\nfull output:\n%s", want, s)
		}
	}
}

func TestGenerateTypeScript_OptionalProperties(t *testing.T) {
	entry := &plugins.CatalogEntry{
		PluginID: "test",
		Version:  "0.1.0",
		Actions: []plugins.ActionDescriptor{
			{
				ID: "test.do@1",
				InputSchema: map[string]any{
					"type": "object",
					"properties": map[string]any{
						"name":  map[string]any{"type": "string"},
						"label": map[string]any{"type": "string"},
					},
					"required": []any{"name"},
				},
				OutputSchema: map[string]any{},
			},
		},
	}

	out, err := GenerateTypeScript(entry)
	if err != nil {
		t.Fatalf("GenerateTypeScript() error: %v", err)
	}
	s := string(out)

	// "name" is required → no "?"
	if !strings.Contains(s, "name: string;") {
		t.Errorf("expected required property without '?'\n\n%s", s)
	}
	// "label" is optional → has "?"
	if !strings.Contains(s, "label?: string;") {
		t.Errorf("expected optional property with '?'\n\n%s", s)
	}
}

func TestGenerateTypeScript_NestedObject(t *testing.T) {
	entry := &plugins.CatalogEntry{
		PluginID: "test",
		Version:  "0.1.0",
		Actions: []plugins.ActionDescriptor{
			{
				ID: "test.nested@1",
				InputSchema: map[string]any{
					"type": "object",
					"properties": map[string]any{
						"config": map[string]any{
							"type": "object",
							"properties": map[string]any{
								"host": map[string]any{"type": "string"},
								"port": map[string]any{"type": "integer"},
							},
							"required": []any{"host"},
						},
					},
					"required": []any{"config"},
				},
				OutputSchema: map[string]any{},
			},
		},
	}

	out, err := GenerateTypeScript(entry)
	if err != nil {
		t.Fatalf("GenerateTypeScript() error: %v", err)
	}
	s := string(out)

	if !strings.Contains(s, "host: string;") {
		t.Errorf("expected nested required property\n\n%s", s)
	}
	if !strings.Contains(s, "port?: number;") {
		t.Errorf("expected nested optional property\n\n%s", s)
	}
}

func TestGenerateTypeScript_ArrayOfObjects(t *testing.T) {
	entry := &plugins.CatalogEntry{
		PluginID: "test",
		Version:  "0.1.0",
		Actions: []plugins.ActionDescriptor{
			{
				ID:          "test.list@1",
				InputSchema: map[string]any{},
				OutputSchema: map[string]any{
					"type": "object",
					"properties": map[string]any{
						"items": map[string]any{
							"type": "array",
							"items": map[string]any{
								"type": "object",
								"properties": map[string]any{
									"id":   map[string]any{"type": "string"},
									"name": map[string]any{"type": "string"},
								},
								"required": []any{"id"},
							},
						},
					},
					"required": []any{"items"},
				},
			},
		},
	}

	out, err := GenerateTypeScript(entry)
	if err != nil {
		t.Fatalf("GenerateTypeScript() error: %v", err)
	}
	s := string(out)

	if !strings.Contains(s, "Array<{") {
		t.Errorf("expected Array<{...}> for array of objects\n\n%s", s)
	}
	if !strings.Contains(s, "id: string;") {
		t.Errorf("expected id property inside array items\n\n%s", s)
	}
}

func TestGenerateTypeScript_EnumUnion(t *testing.T) {
	entry := &plugins.CatalogEntry{
		PluginID: "test",
		Version:  "0.1.0",
		Actions: []plugins.ActionDescriptor{
			{
				ID: "test.choose@1",
				InputSchema: map[string]any{
					"type": "object",
					"properties": map[string]any{
						"mode": map[string]any{
							"enum": []any{"fast", "slow", "auto"},
						},
					},
					"required": []any{"mode"},
				},
				OutputSchema: map[string]any{},
			},
		},
	}

	out, err := GenerateTypeScript(entry)
	if err != nil {
		t.Fatalf("GenerateTypeScript() error: %v", err)
	}
	s := string(out)

	if !strings.Contains(s, `"fast" | "slow" | "auto"`) {
		t.Errorf("expected union type for enum\n\n%s", s)
	}
}

func TestGenerateTypeScript_NoActions(t *testing.T) {
	entry := &plugins.CatalogEntry{
		PluginID: "empty",
		Version:  "0.1.0",
		Connectors: []plugins.ConnectorDescriptor{
			{
				Type:        "empty.db@1",
				Description: "A database connection.",
				ConfigSchema: map[string]any{
					"type": "object",
					"properties": map[string]any{
						"url": map[string]any{"type": "string"},
					},
					"required": []any{"url"},
				},
			},
		},
	}

	out, err := GenerateTypeScript(entry)
	if err != nil {
		t.Fatalf("GenerateTypeScript() error: %v", err)
	}
	s := string(out)

	if !strings.Contains(s, "export interface DbConfig {") {
		t.Errorf("expected connector config interface\n\n%s", s)
	}
	if strings.Contains(s, "Input") || strings.Contains(s, "Output") {
		t.Errorf("expected no action interfaces\n\n%s", s)
	}
}

func TestGenerateTypeScript_NoConnectors(t *testing.T) {
	entry := &plugins.CatalogEntry{
		PluginID: "text",
		Version:  "1.0.0",
		Actions: []plugins.ActionDescriptor{
			{
				ID:           "text.uppercase@1",
				InputSchema:  map[string]any{"type": "object"},
				OutputSchema: map[string]any{"type": "object"},
			},
		},
	}

	out, err := GenerateTypeScript(entry)
	if err != nil {
		t.Fatalf("GenerateTypeScript() error: %v", err)
	}
	s := string(out)

	if !strings.Contains(s, "export interface UppercaseInput {") {
		t.Errorf("expected action interfaces\n\n%s", s)
	}
	if strings.Contains(s, "Config") {
		t.Errorf("expected no connector config interface\n\n%s", s)
	}
}

func TestGenerateTypeScript_EmptyPlugin(t *testing.T) {
	entry := &plugins.CatalogEntry{
		PluginID: "noop",
		Version:  "0.0.1",
	}

	out, err := GenerateTypeScript(entry)
	if err != nil {
		t.Fatalf("GenerateTypeScript() error: %v", err)
	}
	s := string(out)

	if strings.Contains(s, "export namespace") {
		t.Errorf("expected no namespace for empty plugin\n\n%s", s)
	}
	if !strings.Contains(s, "no actions or connectors") {
		t.Errorf("expected comment about empty plugin\n\n%s", s)
	}
}

func TestGenerateTypeScript_Connector(t *testing.T) {
	entry := &plugins.CatalogEntry{
		PluginID: "postgresql",
		Version:  "1.0.0",
		Actions: []plugins.ActionDescriptor{
			{
				ID:           "postgresql.query@1",
				InputSchema:  map[string]any{"type": "object", "properties": map[string]any{"sql": map[string]any{"type": "string"}}, "required": []any{"sql"}},
				OutputSchema: map[string]any{"type": "object"},
			},
		},
		Connectors: []plugins.ConnectorDescriptor{
			{
				Type:        "postgresql.connection@1",
				Description: "A PostgreSQL database connection.",
				ConfigSchema: map[string]any{
					"type": "object",
					"properties": map[string]any{
						"host":     map[string]any{"type": "string"},
						"port":     map[string]any{"type": "integer"},
						"database": map[string]any{"type": "string"},
					},
					"required": []any{"host", "database"},
				},
			},
		},
	}

	out, err := GenerateTypeScript(entry)
	if err != nil {
		t.Fatalf("GenerateTypeScript() error: %v", err)
	}
	s := string(out)

	if !strings.Contains(s, "export namespace Postgresql {") {
		t.Errorf("expected namespace\n\n%s", s)
	}
	if !strings.Contains(s, "export interface QueryInput {") {
		t.Errorf("expected action input\n\n%s", s)
	}
	if !strings.Contains(s, "export interface ConnectionConfig {") {
		t.Errorf("expected connector config\n\n%s", s)
	}
	if !strings.Contains(s, "host: string;") {
		t.Errorf("expected required host property\n\n%s", s)
	}
	if !strings.Contains(s, "port?: number;") {
		t.Errorf("expected optional port property\n\n%s", s)
	}
}

func TestSchemaNoType(t *testing.T) {
	schema := map[string]any{"description": "something opaque"}
	got := schemaToTS(schema, "")
	if got != "unknown" {
		t.Errorf("schemaToTS(no type) = %q, want %q", got, "unknown")
	}
}
