// Package codegen generates typed source code from plugin action and
// connector descriptors (JSON Schema). First target language: TypeScript.
package codegen

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/lucasglmt/patchcord/internal/plugins"
)

// header is written at the top of every generated file.
const header = "// Code generated by patchcord dev codegen — DO NOT EDIT."

// GenerateTypeScript converts a CatalogEntry into a complete .ts file
// containing one namespace (PascalCase of the plugin id) with Input/Output
// interfaces for every action, a type guard function for every Output, and
// a Config interface for every connector.
//
// namespace overrides the auto-detected namespace name. When empty, the
// namespace is inferred from the common domain prefix of the plugin's
// action ids (e.g. actions "imap.list-messages@1" and "imap.get-message@1"
// share the domain "imap" → namespace "Imap"). If no common domain exists,
// the plugin id itself is used as a fallback.
func GenerateTypeScript(entry *plugins.CatalogEntry, namespace string) ([]byte, error) {
	var buf bytes.Buffer

	fmt.Fprintln(&buf, header)
	fmt.Fprintf(&buf, "// Plugin: %s v%s\n", entry.PluginID, entry.Version)

	domain := inferDomain(entry)
	ns := namespace
	if ns == "" {
		ns = toPascalCase(domain)
	}

	if len(entry.Actions) == 0 && len(entry.Connectors) == 0 {
		fmt.Fprintf(&buf, "\n// Plugin %q declares no actions or connectors.\n", entry.PluginID)
		return buf.Bytes(), nil
	}

	fmt.Fprintf(&buf, "\nexport namespace %s {\n", ns)

	for i, action := range entry.Actions {
		base := actionTypeName(action.ID, domain)

		if action.Description != "" {
			fmt.Fprintf(&buf, "  /** %s */\n", action.Description)
		}
		writeInterface(&buf, base+"Input", action.InputSchema, "  ")
		fmt.Fprintln(&buf)
		writeInterface(&buf, base+"Output", action.OutputSchema, "  ")
		fmt.Fprintln(&buf)
		writeTypeGuard(&buf, base+"Output", action.OutputSchema, "  ")

		if i < len(entry.Actions)-1 || len(entry.Connectors) > 0 {
			fmt.Fprintln(&buf)
		}
	}

	for i, conn := range entry.Connectors {
		base := connectorTypeName(conn.Type, domain)

		if conn.Description != "" {
			fmt.Fprintf(&buf, "  /** %s */\n", conn.Description)
		}
		writeInterface(&buf, base+"Config", conn.ConfigSchema, "  ")

		if i < len(entry.Connectors)-1 {
			fmt.Fprintln(&buf)
		}
	}

	fmt.Fprintln(&buf, "}")

	return buf.Bytes(), nil
}

// inferDomain finds the common domain prefix shared by a plugin's action
// ids and connector types. For actions ["imap.list-messages@1",
// "imap.get-message@1"] and connector ["imap.connection@1"], the domain is
// "imap". When no common domain exists, the plugin id is returned as a
// fallback.
func inferDomain(entry *plugins.CatalogEntry) string {
	var candidate string

	if len(entry.Actions) > 0 {
		candidate = idDomain(entry.Actions[0].ID)
		for _, a := range entry.Actions[1:] {
			if idDomain(a.ID) != candidate {
				candidate = ""
				break
			}
		}
	}

	if candidate == "" && len(entry.Connectors) > 0 {
		candidate = idDomain(entry.Connectors[0].Type)
	}

	if candidate == "" {
		return entry.PluginID
	}

	return candidate
}

// idDomain returns the part before the first "." in a qualified identifier
// ("imap.list-messages@1" → "imap"). Returns "" if there is no ".".
func idDomain(qualifiedID string) string {
	if dot := strings.Index(qualifiedID, "."); dot > 0 {
		return qualifiedID[:dot]
	}
	return ""
}

// actionTypeName strips the domain prefix and version suffix from an
// action id, then converts the remainder to PascalCase.
// actionTypeName("imap.list-messages@1", "imap") → "ListMessages".
func actionTypeName(actionID, domain string) string {
	name := actionID

	// Strip domain prefix ("imap.list-messages@1" → "list-messages@1").
	if domain != "" && strings.HasPrefix(name, domain+".") {
		name = name[len(domain)+1:]
	}

	// Strip version suffix ("list-messages@1" → "list-messages").
	if at := strings.LastIndex(name, "@"); at >= 0 {
		name = name[:at]
	}

	return toPascalCase(name)
}

// connectorTypeName strips the domain prefix and version suffix from a
// connector type, then converts the remainder to PascalCase.
// connectorTypeName("imap.connection@1", "imap") → "Connection".
func connectorTypeName(connType, domain string) string {
	name := connType

	if domain != "" && strings.HasPrefix(name, domain+".") {
		name = name[len(domain)+1:]
	}

	if at := strings.LastIndex(name, "@"); at >= 0 {
		name = name[:at]
	}

	return toPascalCase(name)
}

// toPascalCase splits on "-", "_", or "." and capitalises each segment.
func toPascalCase(s string) string {
	var b strings.Builder

	upper := true
	for _, r := range s {
		switch r {
		case '-', '_', '.':
			upper = true
		default:
			if upper {
				b.WriteString(strings.ToUpper(string(r)))
				upper = false
			} else {
				b.WriteRune(r)
			}
		}
	}

	return b.String()
}

// writeTypeGuard writes a TypeScript type guard function that narrows
// unknown to the given interface by checking required top-level properties
// and their primitive types. This lets callers safely narrow an API
// response (typed as unknown or any) to the generated Output interface:
//
//	const data: unknown = await fetchResult();
//	if (Imap.isListMessagesOutput(data)) { /* data is ListMessagesOutput */ }
func writeTypeGuard(buf *bytes.Buffer, ifaceName string, schema map[string]any, indent string) {
	fnName := "is" + ifaceName
	fmt.Fprintf(buf, "%sexport function %s(value: unknown): value is %s {\n", indent, fnName, ifaceName)
	fmt.Fprintf(buf, "%s  if (typeof value !== \"object\" || value === null) return false;\n", indent)

	required := requiredSet(schema)
	props, _ := schema["properties"].(map[string]any)

	// Collect checks for required properties only — optional ones may be
	// absent, so testing them would reject valid payloads.
	var checks []string
	for _, key := range sortedKeys(props) {
		if !required[key] {
			continue
		}
		propSchema, ok := props[key].(map[string]any)
		if !ok {
			continue
		}
		checks = append(checks, typeCheck(key, propSchema))
	}

	if len(checks) == 0 {
		// No required properties — the guard can only confirm it's an object.
		fmt.Fprintf(buf, "%s  return true;\n", indent)
	} else {
		fmt.Fprintf(buf, "%s  const obj = value as Record<string, unknown>;\n", indent)
		fmt.Fprintf(buf, "%s  return %s;\n", indent, strings.Join(checks, " && "))
	}

	fmt.Fprintf(buf, "%s}\n", indent)
}

// typeCheck returns a TypeScript expression that validates a single
// required property exists and has the expected runtime type.
func typeCheck(key string, schema map[string]any) string {
	typ, _ := schema["type"].(string)

	switch typ {
	case "string":
		return fmt.Sprintf("typeof obj.%s === \"string\"", key)
	case "number", "integer":
		return fmt.Sprintf("typeof obj.%s === \"number\"", key)
	case "boolean":
		return fmt.Sprintf("typeof obj.%s === \"boolean\"", key)
	case "array":
		return fmt.Sprintf("Array.isArray(obj.%s)", key)
	case "object":
		return fmt.Sprintf("typeof obj.%s === \"object\" && obj.%s !== null", key, key)
	default:
		// Unknown or complex type — just confirm the key exists.
		return fmt.Sprintf("\"%s\" in obj", key)
	}
}

// writeInterface writes a TypeScript export interface block from a JSON
// Schema object. If the schema is nil or empty, it writes an empty
// interface.
func writeInterface(buf *bytes.Buffer, name string, schema map[string]any, indent string) {
	fmt.Fprintf(buf, "%sexport interface %s {\n", indent, name)

	if schema == nil {
		fmt.Fprintf(buf, "%s}\n", indent)
		return
	}

	props, _ := schema["properties"].(map[string]any)
	required := requiredSet(schema)

	if props == nil {
		fmt.Fprintf(buf, "%s}\n", indent)
		return
	}

	// Sort property names for deterministic output.
	keys := sortedKeys(props)

	for _, key := range keys {
		propSchema, ok := props[key].(map[string]any)
		if !ok {
			continue
		}

		if desc, ok := propSchema["description"].(string); ok && desc != "" {
			fmt.Fprintf(buf, "%s  /** %s */\n", indent, desc)
		}

		opt := "?"
		if required[key] {
			opt = ""
		}

		tsType := schemaToTS(propSchema, indent+"  ")
		fmt.Fprintf(buf, "%s  %s%s: %s;\n", indent, key, opt, tsType)
	}

	fmt.Fprintf(buf, "%s}\n", indent)
}

// schemaToTS converts a single JSON Schema property definition to a
// TypeScript type expression.
func schemaToTS(schema map[string]any, indent string) string {
	// Enum takes priority — produce a union of literals.
	if enumVals, ok := schema["enum"].([]any); ok && len(enumVals) > 0 {
		return enumToTS(enumVals)
	}

	typ, _ := schema["type"].(string)

	switch typ {
	case "string":
		return "string"
	case "number", "integer":
		return "number"
	case "boolean":
		return "boolean"
	case "array":
		return arrayToTS(schema, indent)
	case "object":
		return objectToTS(schema, indent)
	default:
		return "unknown"
	}
}

// enumToTS converts a JSON Schema enum array to a TypeScript union of
// string literals. Non-string values are rendered via fmt.Sprintf.
func enumToTS(vals []any) string {
	parts := make([]string, len(vals))
	for i, v := range vals {
		switch v := v.(type) {
		case string:
			parts[i] = fmt.Sprintf("%q", v)
		default:
			parts[i] = fmt.Sprintf("%v", v)
		}
	}
	return strings.Join(parts, " | ")
}

// arrayToTS handles {"type":"array","items":{...}}.
func arrayToTS(schema map[string]any, indent string) string {
	items, ok := schema["items"].(map[string]any)
	if !ok {
		return "Array<unknown>"
	}

	inner := schemaToTS(items, indent)

	// Wrap union types in parens for clarity: Array<"a" | "b">.
	if strings.Contains(inner, "|") {
		return fmt.Sprintf("Array<%s>", inner)
	}

	return fmt.Sprintf("Array<%s>", inner)
}

// objectToTS handles inline {"type":"object","properties":{...}}.
func objectToTS(schema map[string]any, indent string) string {
	props, ok := schema["properties"].(map[string]any)
	if !ok {
		return "Record<string, unknown>"
	}

	required := requiredSet(schema)
	keys := sortedKeys(props)

	var buf bytes.Buffer
	buf.WriteString("{\n")

	for _, key := range keys {
		propSchema, ok := props[key].(map[string]any)
		if !ok {
			continue
		}

		if desc, ok := propSchema["description"].(string); ok && desc != "" {
			fmt.Fprintf(&buf, "%s  /** %s */\n", indent, desc)
		}

		opt := "?"
		if required[key] {
			opt = ""
		}

		tsType := schemaToTS(propSchema, indent+"  ")
		fmt.Fprintf(&buf, "%s  %s%s: %s;\n", indent, key, opt, tsType)
	}

	fmt.Fprintf(&buf, "%s}", indent)
	return buf.String()
}

// requiredSet returns the set of required property names from a JSON
// Schema object definition.
func requiredSet(schema map[string]any) map[string]bool {
	reqSlice, _ := schema["required"].([]any)
	m := make(map[string]bool, len(reqSlice))
	for _, v := range reqSlice {
		if s, ok := v.(string); ok {
			m[s] = true
		}
	}
	return m
}

// sortedKeys returns the keys of a map in sorted order.
func sortedKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
