package plugins

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
)

const scaffoldMainGo = `package main

import (
	"context"
	"fmt"
	"os"

	patchcord "github.com/lucasglmt/patchcord/sdk/go-plugin"
)

type exampleAction struct{}

func (exampleAction) ID() string { return "example.echo@1" }

func (exampleAction) Description() string { return "Returns the given value unchanged." }

func (exampleAction) InputSchema() patchcord.Schema {
	return patchcord.Schema{
		"type": "object",
		"properties": map[string]any{
			"value": map[string]any{"type": "string"},
		},
		"required": []any{"value"},
	}
}

func (exampleAction) OutputSchema() patchcord.Schema {
	return patchcord.Schema{
		"type": "object",
		"properties": map[string]any{
			"value": map[string]any{"type": "string"},
		},
		"required": []any{"value"},
	}
}

func (exampleAction) Run(_ context.Context, input patchcord.ActionInput, _ *patchcord.ConnectorConfig) (patchcord.ActionOutput, error) {
	value, ok := input["value"].(string)
	if !ok {
		return nil, fmt.Errorf("input %%q must be a string", "value")
	}
	return patchcord.ActionOutput{"value": value}, nil
}

func main() {
	plugin := patchcord.Plugin{
		Manifest: patchcord.Manifest{
			ID:      %q,
			Version: %q,
		},
		Actions: []patchcord.Action{
			exampleAction{},
		},
	}

	if err := patchcord.Serve(plugin); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
`

const scaffoldReadmeTemplate = `# %s

Generated by ` + "`patchcord plugin new`" + `. Replace ` + "`exampleAction`" + ` in
main.go with your own action(s), then:

	go build -o binaries/%s/plugin .
	patchcord plugin pack . -o %s-%s.patchcord-plugin
	patchcord plugin install %s-%s.patchcord-plugin

manifest.json only declares an executable for the platform you scaffolded
on (%s) — add more entries to its "executables" map for other platforms
you cross-compile for.
`

// Scaffold writes a minimal Go plugin (main.go, one example action) and a
// manifest.json declaring an executable for the current platform, into
// dir — enough to `go build` then `plugin pack` without hand-editing the
// manifest. It returns an error if dir already exists and is not empty.
func Scaffold(dir, id, version string) error {
	if err := ensureEmptyDir(dir); err != nil {
		return err
	}

	mainGo := fmt.Sprintf(scaffoldMainGo, id, version)
	if err := os.WriteFile(filepath.Join(dir, "main.go"), []byte(mainGo), 0o644); err != nil {
		return fmt.Errorf("write main.go: %w", err)
	}

	platform := runtime.GOOS + "-" + runtime.GOARCH
	manifest := packageManifestJSON{
		SchemaVersion:   1,
		Kind:            packageManifestKind,
		ID:              id,
		Version:         version,
		ProtocolVersion: CurrentProtocolVersion,
		Permissions:     []string{},
		Executables: map[string]string{
			platform: fmt.Sprintf("binaries/%s/plugin", platform),
		},
	}
	manifestJSON, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return fmt.Errorf("encode manifest.json: %w", err)
	}
	if err := os.WriteFile(filepath.Join(dir, PackageManifestFileName), manifestJSON, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", PackageManifestFileName, err)
	}

	readme := fmt.Sprintf(scaffoldReadmeTemplate, id, platform, id, version, id, version, platform)
	if err := os.WriteFile(filepath.Join(dir, "README.md"), []byte(readme), 0o644); err != nil {
		return fmt.Errorf("write README.md: %w", err)
	}

	return nil
}

// ensureEmptyDir creates dir if it doesn't exist yet, or errors if it
// exists and already has entries — same rule as apps.Scaffold and
// bundles.Scaffold.
func ensureEmptyDir(dir string) error {
	entries, err := os.ReadDir(dir)
	if err == nil {
		if len(entries) > 0 {
			return fmt.Errorf("%q already exists and is not empty", dir)
		}
		return nil
	}
	if !os.IsNotExist(err) {
		return fmt.Errorf("check %q: %w", dir, err)
	}

	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create %q: %w", dir, err)
	}
	return nil
}
