package plugins

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
)

const scaffoldGoVersion = "1.25.3"

const scaffoldGoModTemplate = `module %s

go %s
`

const scaffoldMainGo = `package main

import (
	"context"
	"fmt"
	"os"

	patchcord "github.com/lucasglmt/patchcord/sdk/go-plugin"
)

type exampleAction struct{}

func (exampleAction) ID() string { return "example.echo@1" }

func (exampleAction) Description() string { return "Returns the given value unchanged." }

func (exampleAction) InputSchema() patchcord.Schema {
	return patchcord.Schema{
		"type": "object",
		"properties": map[string]any{
			"value": map[string]any{"type": "string"},
		},
		"required": []any{"value"},
	}
}

func (exampleAction) OutputSchema() patchcord.Schema {
	return patchcord.Schema{
		"type": "object",
		"properties": map[string]any{
			"value": map[string]any{"type": "string"},
		},
		"required": []any{"value"},
	}
}

func (exampleAction) Run(_ context.Context, input patchcord.ActionInput, _ *patchcord.ConnectorConfig) (patchcord.ActionOutput, error) {
	value, ok := input["value"].(string)
	if !ok {
		return nil, fmt.Errorf("input %%q must be a string", "value")
	}
	return patchcord.ActionOutput{"value": value}, nil
}

func main() {
	plugin := patchcord.Plugin{
		Manifest: patchcord.Manifest{
			ID:      %q,
			Version: %q,
		},
		Actions: []patchcord.Action{
			exampleAction{},
		},
	}

	if err := patchcord.Serve(plugin); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
`

const scaffoldReadmeTemplate = `# %s

Generated by ` + "`patchcord plugin new`" + ` as a standalone Go module.
Full guide: https://lucasglmt.github.io/patchcord/plugins/writing-a-plugin-go.html
(all docs: https://lucasglmt.github.io/patchcord/).

Replace ` + "`exampleAction`" + ` in ` + "`main.go`" + ` with your own action(s), then:

	go mod tidy
	go build -o binaries/%s/plugin .
	patchcord plugin pack . -o %s-%s.patchcord-plugin
	patchcord plugin install %s-%s.patchcord-plugin

manifest.json only declares an executable for the platform you scaffolded
on (%s) — add more entries to its "executables" map for other platforms
you cross-compile for.

This plugin imports only the public Go SDK:

	github.com/lucasglmt/patchcord/sdk/go-plugin

sdk/go-plugin and the plugin protocol it wraps (github.com/lucasglmt/patchcord/api/plugin)
are independently versioned nested modules of the Patchcord monorepo — see
docs/adr/0066 in that repo. If you are testing against a local Patchcord
checkout instead of released module versions, add temporary replace
directives for both:

	go mod edit -replace github.com/lucasglmt/patchcord/sdk/go-plugin=/path/to/patchcord/sdk/go-plugin
	go mod edit -replace github.com/lucasglmt/patchcord/api/plugin=/path/to/patchcord/api/plugin
`

const scaffoldMakefileTemplate = `.PHONY: deps build pack install-local

PLUGIN_ID := %s
PLUGIN_VERSION := %s
PLATFORM ?= $(shell go env GOOS)-$(shell go env GOARCH)
BINARY := binaries/$(PLATFORM)/plugin
PACKAGE := $(PLUGIN_ID)-$(PLUGIN_VERSION).patchcord-plugin

deps:
	go mod tidy

build: deps
	mkdir -p $(dir $(BINARY))
	go build -o $(BINARY) .

pack: build
	patchcord plugin pack . -o $(PACKAGE)

install-local: pack
	patchcord plugin install $(PACKAGE)
`

const scaffoldGitignore = `binaries/
*.patchcord-plugin
`

// scaffoldAgentsMD is written at dir's root, alongside go.mod — not part of
// the plugin package itself (`plugin pack` only archives what manifest.json
// declares, so it's never distributed), but the first thing a coding agent
// working in this directory should read. AGENTS.md, not CLAUDE.md — same
// choice as apps.Scaffold/bundles.Scaffold, see apps.scaffoldAgentsMD's doc
// comment for why (emerging cross-tool convention, avoids two files with
// the same content to keep in sync).
const scaffoldAgentsMD = `# Agent instructions — Patchcord plugin

This directory is a standalone Go module scaffolded by ` + "`patchcord plugin new`" + `:
a Patchcord plugin, an independent process the agent supervises and talks
to over the plugin protocol — never linked into the core. It imports only
` + "`github.com/lucasglmt/patchcord/sdk/go-plugin`" + ` and the public protocol it
wraps, never an ` + "`internal/`" + ` package (non-negotiable #4, ` + "`CLAUDE.md`" + `
section 1).

## Ground yourself in the real catalog and protocol, don't guess

Register this agent's MCP server rather than hallucinating action ids,
connector types, or schema shapes already in use elsewhere:

` + "```bash" + `
claude mcp add patchcord -- patchcord mcp serve   # Claude Code
codex mcp add patchcord -- patchcord mcp serve    # Codex
` + "```" + `

Then use ` + "`list_plugins`" + `/` + "`list_actions`" + `/` + "`describe_action`" + `/` + "`list_connectors`" + `/
` + "`describe_connector`" + ` to see what's already installed before picking this
plugin's action ids and connector types — avoid colliding with an existing
id, and match the conventions already in use (e.g. ` + "`<domain>.<verb>@<version>`" + `).
Once this plugin is installed locally (see the dev loop below),
` + "`describe_action`" + ` also confirms the schema it actually negotiated matches
what ` + "`InputSchema()`" + `/` + "`OutputSchema()`" + ` declare. See
[MCP command reference](https://github.com/lucasglmt/patchcord/blob/main/docs/book/src/cli/commands/mcp.md).

Full plugin-authoring guide:
[Writing a Plugin in Go](https://github.com/lucasglmt/patchcord/blob/main/docs/book/src/plugins/writing-a-plugin-go.md)
(all docs: https://lucasglmt.github.io/patchcord/plugins/).

## Protocol basics

Replace ` + "`exampleAction`" + ` in ` + "`main.go`" + ` with your own action(s). Each action
implements ` + "`patchcord.Action`" + `: ` + "`ID()`" + `, ` + "`Description()`" + `,
` + "`InputSchema()`" + `, ` + "`OutputSchema()`" + ` and ` + "`Run(ctx, input, connector)`" + ` — the first
three are mandatory, not optional
([ADR-0062](https://github.com/lucasglmt/patchcord/blob/main/docs/adr/0062-descripteurs-schema-actions-et-connecteurs.md)).
If an action needs a bound connector (e.g. a database connection), declare
a ` + "`patchcord.Connector`" + ` type on ` + "`Plugin.Connectors`" + ` with a description and a
JSON Schema for its non-secret configuration only — a secret never appears
in a schema
([ADR-0009](https://github.com/lucasglmt/patchcord/blob/main/docs/adr/0009-secrets-jamais-dans-workflows.md)).
Implement ` + "`ConnectorTester`" + ` and set ` + "`Plugin.Tester`" + ` to support
` + "`patchcord connector test`" + `; leaving it unset is fine, it just reports
` + "`Unimplemented`" + `.

## Dev loop

` + "```bash" + `
make build          # go build into binaries/<platform>/plugin
make pack           # patchcord plugin pack . -o <id>-<version>.patchcord-plugin
make install-local  # pack, then patchcord plugin install the result
patchcord plugin inspect <id>
` + "```" + `

manifest.json only declares an executable for the platform this was
scaffolded on — add more entries to its ` + "`executables`" + ` map when
cross-compiling for others. A change to the installed catalog takes effect
the next time ` + "`patchcord serve`" + ` (or ` + "`workflow run`" + `/` + "`connector test`" + `) starts,
not immediately.
`

// Scaffold writes a minimal standalone Go plugin module using id as both
// the plugin id and Go module path. See ScaffoldWithModule for details.
func Scaffold(dir, id, version string) error {
	return ScaffoldWithModule(dir, id, version, id)
}

// ScaffoldWithModule writes a minimal standalone Go plugin module
// (go.mod, main.go, one example action, manifest.json, README.md,
// Makefile, .gitignore) into dir. The generated plugin imports only the
// public Go SDK and the package manifest declares an executable for the
// current platform, enough to `go build` then `plugin pack` without
// hand-editing the manifest. It returns an error if dir already exists and
// is not empty.
func ScaffoldWithModule(dir, id, version, modulePath string) error {
	if err := ensureEmptyDir(dir); err != nil {
		return err
	}

	if modulePath == "" {
		modulePath = id
	}

	goMod := fmt.Sprintf(scaffoldGoModTemplate, modulePath, scaffoldGoVersion)
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(goMod), 0o644); err != nil {
		return fmt.Errorf("write go.mod: %w", err)
	}

	mainGo := fmt.Sprintf(scaffoldMainGo, id, version)
	if err := os.WriteFile(filepath.Join(dir, "main.go"), []byte(mainGo), 0o644); err != nil {
		return fmt.Errorf("write main.go: %w", err)
	}

	platform := runtime.GOOS + "-" + runtime.GOARCH
	manifest := packageManifestJSON{
		SchemaVersion:   1,
		Kind:            packageManifestKind,
		ID:              id,
		Version:         version,
		ProtocolVersion: CurrentProtocolVersion,
		Permissions:     []string{},
		Executables: map[string]string{
			platform: fmt.Sprintf("binaries/%s/plugin", platform),
		},
	}
	manifestJSON, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return fmt.Errorf("encode manifest.json: %w", err)
	}
	if err := os.WriteFile(filepath.Join(dir, PackageManifestFileName), manifestJSON, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", PackageManifestFileName, err)
	}

	readme := fmt.Sprintf(scaffoldReadmeTemplate, id, platform, id, version, id, version, platform)
	if err := os.WriteFile(filepath.Join(dir, "README.md"), []byte(readme), 0o644); err != nil {
		return fmt.Errorf("write README.md: %w", err)
	}

	makefile := fmt.Sprintf(scaffoldMakefileTemplate, id, version)
	if err := os.WriteFile(filepath.Join(dir, "Makefile"), []byte(makefile), 0o644); err != nil {
		return fmt.Errorf("write Makefile: %w", err)
	}

	if err := os.WriteFile(filepath.Join(dir, ".gitignore"), []byte(scaffoldGitignore), 0o644); err != nil {
		return fmt.Errorf("write .gitignore: %w", err)
	}

	if err := os.WriteFile(filepath.Join(dir, "AGENTS.md"), []byte(scaffoldAgentsMD), 0o644); err != nil {
		return fmt.Errorf("write AGENTS.md: %w", err)
	}

	return nil
}

// ensureEmptyDir creates dir if it doesn't exist yet, or errors if it
// exists and already has entries — same rule as apps.Scaffold and
// bundles.Scaffold.
func ensureEmptyDir(dir string) error {
	entries, err := os.ReadDir(dir)
	if err == nil {
		if len(entries) > 0 {
			return fmt.Errorf("%q already exists and is not empty", dir)
		}
		return nil
	}
	if !os.IsNotExist(err) {
		return fmt.Errorf("check %q: %w", dir, err)
	}

	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create %q: %w", dir, err)
	}
	return nil
}
