package bundles

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/lucasglmt/patchcord/internal/apps"
	"github.com/lucasglmt/patchcord/internal/workflow"
)

const scaffoldManifestTemplate = `id: %s
version: "%s"
app: app
workflows:
  - workflows/main.yaml
requires_plugins: []
`

// scaffoldViteManifestTemplate points app at app/dist rather than app: a
// Vite project's patchcord-app.yaml only exists there after `npm run
// build` copies it out of app/public — see apps.ScaffoldVite.
const scaffoldViteManifestTemplate = `id: %s
version: "%s"
app: app/dist
workflows:
  - workflows/main.yaml
requires_plugins: []
`

// scaffoldAgentsMD is written at dir's root, alongside bundle.yaml — not
// part of the bundle itself (bundle pack never archives anything beyond
// what bundle.yaml declares, so it's never distributed), but the first
// thing a coding agent working in this directory should read. Shared by
// Scaffold and ScaffoldVite: the guidance here (MCP, workflows, plugin
// dependencies) doesn't depend on which app template was used —
// app-template-specific guidance lives in app/AGENTS.md instead (see
// apps.Scaffold/apps.ScaffoldVite). AGENTS.md, not CLAUDE.md — see
// apps.scaffoldAgentsMD's doc comment for why.
const scaffoldAgentsMD = `# Agent instructions — Patchcord bundle

This directory is a Patchcord bundle: an embedded application (` + "`app/`" + `)
plus its workflows (` + "`workflows/`" + `) plus its plugin dependencies, packaged
together by ` + "`bundle.yaml`" + `. Generated by ` + "`patchcord bundle new`" + `. See
` + "`app/AGENTS.md`" + ` for application-specific guidance.

## Ground yourself in the real catalog, don't guess

Register this agent's MCP server rather than hallucinating action ids or
field names:

` + "```bash" + `
claude mcp add patchcord -- patchcord mcp serve   # Claude Code
codex mcp add patchcord -- patchcord mcp serve    # Codex
` + "```" + `

Then use ` + "`list_actions`" + `/` + "`describe_action`" + `/` + "`list_connectors`" + `/` + "`describe_connector`" + ` to
discover what's actually installed, and ` + "`validate_workflow`" + ` to check a
workflow draft before writing it to disk — it reports a rejected draft as
its normal, successful result, meant to be read and acted on, not as a
failure. ` + "`scaffold_app`" + `/` + "`scaffold_bundle`" + ` are also available as MCP tools.
See [MCP command reference](https://github.com/lucasglmt/patchcord/blob/main/docs/book/src/cli/commands/mcp.md).

## Workflows

` + "`workflows/main.yaml`" + ` is a starting point. A workflow declares a trigger,
then a list of steps; each step ` + "`uses:`" + ` an action id and passes it
` + "`with:`" + `, whose values may be literals or ` + "`${{ ... }}`" + ` expressions
(` + "`workflow.inputs.*`" + `, ` + "`steps.<id>.outputs.*`" + `). See
[Workflow Format](https://github.com/lucasglmt/patchcord/blob/main/docs/book/src/workflows/format.md)
for the full grammar.

` + "```bash" + `
patchcord workflow validate workflows/main.yaml
` + "```" + `

## Plugin dependencies

` + "`bundle.yaml`" + `'s ` + "`requires_plugins`" + ` lists ` + "`id@version`" + ` entries this bundle needs
already installed — it starts empty; a bundle never auto-installs its
dependencies. Add to it as you use new actions.

## Dev loop

` + "```bash" + `
patchcord bundle dev .    # install/update from this directory for local development
patchcord bundle pack .   # package into a .patchcord-bundle archive
` + "```" + `
`

// Scaffold writes a minimal bundle.yaml and AGENTS.md to dir, plus an
// embedded app (delegating to apps.Scaffold) and workflow (delegating to
// workflow.Scaffold) so the result is `bundle pack`-able as-is —
// requires_plugins starts empty since Scaffold has no way to know what
// plugin the bundle should depend on. It returns an error if dir already
// exists and is not empty.
func Scaffold(dir, id, version string) error {
	if err := ensureEmptyDir(dir); err != nil {
		return err
	}

	manifest := fmt.Sprintf(scaffoldManifestTemplate, id, version)
	if err := os.WriteFile(filepath.Join(dir, ManifestFileName), []byte(manifest), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", ManifestFileName, err)
	}

	if err := os.WriteFile(filepath.Join(dir, "AGENTS.md"), []byte(scaffoldAgentsMD), 0o644); err != nil {
		return fmt.Errorf("write AGENTS.md: %w", err)
	}

	if err := apps.Scaffold(filepath.Join(dir, "app"), id, version); err != nil {
		return fmt.Errorf("scaffold embedded app: %w", err)
	}

	workflowsDir := filepath.Join(dir, "workflows")
	if err := os.MkdirAll(workflowsDir, 0o755); err != nil {
		return fmt.Errorf("create %q: %w", workflowsDir, err)
	}
	if err := workflow.Scaffold(filepath.Join(workflowsDir, "main.yaml"), id+"_workflow", 1); err != nil {
		return fmt.Errorf("scaffold embedded workflow: %w", err)
	}

	return nil
}

// ScaffoldVite writes a bundle.yaml to dir, plus an embedded Vite +
// TypeScript project (delegating to apps.ScaffoldVite) and workflow
// (delegating to workflow.Scaffold). Unlike Scaffold, the result is not
// `bundle pack`-able as-is: the embedded app's patchcord-app.yaml only
// exists at app/dist after building it —
//
//	cd dir/app && npm install && npm run build
//
// bundle.yaml's app field already points at app/dist, so `bundle
// pack`/`bundle dev [--watch]` need nothing further once that build has
// run at least once. It returns an error if dir already exists and is not
// empty.
func ScaffoldVite(dir, id, version string) error {
	if err := ensureEmptyDir(dir); err != nil {
		return err
	}

	manifest := fmt.Sprintf(scaffoldViteManifestTemplate, id, version)
	if err := os.WriteFile(filepath.Join(dir, ManifestFileName), []byte(manifest), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", ManifestFileName, err)
	}

	if err := os.WriteFile(filepath.Join(dir, "AGENTS.md"), []byte(scaffoldAgentsMD), 0o644); err != nil {
		return fmt.Errorf("write AGENTS.md: %w", err)
	}

	if err := apps.ScaffoldVite(filepath.Join(dir, "app"), id, version); err != nil {
		return fmt.Errorf("scaffold embedded app: %w", err)
	}

	workflowsDir := filepath.Join(dir, "workflows")
	if err := os.MkdirAll(workflowsDir, 0o755); err != nil {
		return fmt.Errorf("create %q: %w", workflowsDir, err)
	}
	if err := workflow.Scaffold(filepath.Join(workflowsDir, "main.yaml"), id+"_workflow", 1); err != nil {
		return fmt.Errorf("scaffold embedded workflow: %w", err)
	}

	return nil
}

// ensureEmptyDir creates dir if it doesn't exist yet, or errors if it
// exists and already has entries — same rule as apps.Scaffold and
// plugins.Scaffold, kept package-local rather than shared since each is a
// few lines wired into a different set of writes.
func ensureEmptyDir(dir string) error {
	entries, err := os.ReadDir(dir)
	if err == nil {
		if len(entries) > 0 {
			return fmt.Errorf("%q already exists and is not empty", dir)
		}
		return nil
	}
	if !os.IsNotExist(err) {
		return fmt.Errorf("check %q: %w", dir, err)
	}

	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create %q: %w", dir, err)
	}
	return nil
}
