package apps

import (
	"fmt"
	"os"
	"path/filepath"
)

const scaffoldManifestTemplate = `id: %s
version: "%s"
permissions:
  workflows:
    run: []
`

const scaffoldIndexHTML = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>%s</title>
  </head>
  <body>
    <h1>%s</h1>
    <p>Generated by <code>patchcord app new</code>. Build your application
    here, or wire it up to the public API with the TypeScript SDK
    (docs/book/src/sdk-ts/getting-started.md).</p>
  </body>
</html>
`

// Scaffold writes a minimal patchcord-app.yaml and index.html to dir,
// ready for `app pack`/`app install` as-is. It returns an error if dir
// already exists and is not empty — Scaffold never overwrites.
func Scaffold(dir, id, version string) error {
	if err := ensureEmptyDir(dir); err != nil {
		return err
	}

	manifest := fmt.Sprintf(scaffoldManifestTemplate, id, version)
	if err := os.WriteFile(filepath.Join(dir, ManifestFileName), []byte(manifest), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", ManifestFileName, err)
	}

	index := fmt.Sprintf(scaffoldIndexHTML, id, id)
	if err := os.WriteFile(filepath.Join(dir, "index.html"), []byte(index), 0o644); err != nil {
		return fmt.Errorf("write index.html: %w", err)
	}

	return nil
}

// ensureEmptyDir creates dir if it doesn't exist yet, or errors if it
// exists and already has entries — a scaffold command must never silently
// overwrite a directory the caller has already put work into.
func ensureEmptyDir(dir string) error {
	entries, err := os.ReadDir(dir)
	if err == nil {
		if len(entries) > 0 {
			return fmt.Errorf("%q already exists and is not empty", dir)
		}
		return nil
	}
	if !os.IsNotExist(err) {
		return fmt.Errorf("check %q: %w", dir, err)
	}

	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create %q: %w", dir, err)
	}
	return nil
}
