package apps

import (
	"fmt"
	"os"
	"path/filepath"
)

const scaffoldManifestTemplate = `id: %s
version: "%s"
permissions:
  workflows:
    run: []
`

const scaffoldIndexHTML = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>%s</title>
  </head>
  <body>
    <h1>%s</h1>
    <p>Generated by <code>patchcord app new</code>. Build your application
    here, or wire it up to the public API with the TypeScript SDK
    (docs/book/src/sdk-ts/getting-started.md).</p>
  </body>
</html>
`

// Scaffold writes a minimal patchcord-app.yaml and index.html to dir,
// ready for `app pack`/`app install` as-is. It returns an error if dir
// already exists and is not empty — Scaffold never overwrites.
func Scaffold(dir, id, version string) error {
	if err := ensureEmptyDir(dir); err != nil {
		return err
	}

	manifest := fmt.Sprintf(scaffoldManifestTemplate, id, version)
	if err := os.WriteFile(filepath.Join(dir, ManifestFileName), []byte(manifest), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", ManifestFileName, err)
	}

	index := fmt.Sprintf(scaffoldIndexHTML, id, id)
	if err := os.WriteFile(filepath.Join(dir, "index.html"), []byte(index), 0o644); err != nil {
		return fmt.Errorf("write index.html: %w", err)
	}

	return nil
}

const scaffoldVitePackageJSON = `{
  "name": "%s",
  "private": true,
  "version": "%s",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@glmtsolutions/patchcord-sdk": "^0.1.0"
  },
  "devDependencies": {
    "typescript": "^5.7.2",
    "vite": "^6.0.0"
  }
}
`

const scaffoldViteConfig = `import { defineConfig } from "vite";

export default defineConfig({
  // Relative, not "/": the agent serves a built app under /apps/{id}/, a
  // subpath it only learns at install time, never at build time. Vite's
  // default base ("/") emits asset URLs rooted at the domain instead
  // (e.g. "/assets/index-xxxx.js"), which 404s once installed — the
  // browser resolves them against the origin, not against
  // /apps/{id}/index.html. "./" makes every emitted URL relative to
  // index.html itself, so it resolves correctly under any {id}.
  base: "./",
  build: {
    outDir: "dist",
  },
  server: {
    proxy: {
      // Forwarded server-side by Vite's own dev server, so the browser
      // only ever talks to this same origin (localhost:5173) — no CORS
      // involved. Once the agent has at least one admin token, it stops
      // sending permissive CORS headers entirely (ADR-0045), which would
      // otherwise block a direct cross-origin fetch from vite dev to
      // 127.0.0.1:7331. Once built and installed, the app is served by
      // the agent itself at the same origin anyway, so this proxy only
      // matters for "npm run dev".
      "/v1": "http://127.0.0.1:7331",
    },
  },
});
`

const scaffoldViteTSConfig = `{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ESNext",
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "strict": true
  },
  "include": ["src"]
}
`

const scaffoldViteIndexHTML = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>%s</title>
    <script type="module" src="/src/main.ts"></script>
  </head>
  <body>
    <div id="app"></div>
  </body>
</html>
`

const scaffoldViteMainTS = `import { PatchcordClient } from "@glmtsolutions/patchcord-sdk";

// The current origin works in both cases: under ` + "`npm run dev`" + `, vite.config.ts
// proxies /v1 to the agent (127.0.0.1:7331 by default) server-side, so no
// CORS is involved even once the agent has an admin token and stops
// sending permissive CORS headers (ADR-0045). Once built and installed
// (` + "`patchcord app install`/`patchcord bundle dev`" + `), the agent serves this app
// itself at /apps/{id}/ — genuinely same origin, zero configuration needed.
const client = new PatchcordClient({ baseUrl: window.location.origin });

const app = document.querySelector<HTMLDivElement>("#app")!;
app.innerHTML = ` + "`" + `
  <h1>%s</h1>
  <p>Generated by <code>patchcord app new --template vite</code>. Build your
  application here — @glmtsolutions/patchcord-sdk is already wired up above, see
  docs/book/src/sdk-ts/getting-started.md for the rest of its API.</p>
  <p>Agent status: <span id="status">checking...</span></p>
` + "`" + `;

client.system
  .health()
  .then((status) => {
    document.querySelector("#status")!.textContent = status.status;
  })
  .catch(() => {
    document.querySelector("#status")!.textContent = "unreachable";
  });
`

// scaffoldViteManifestTemplate mirrors scaffoldManifestTemplate but lives
// under public/ instead of dir's root: Vite copies everything under
// public/ verbatim into dist/ on build, which is what turns a plain Vite
// project into an installable app directory once built (see the comment
// below on where dist ends up).
const scaffoldViteManifestTemplate = scaffoldManifestTemplate

const scaffoldViteGitignore = `node_modules/
dist/
`

// scaffoldViteEnvDTS declares Vite's own ambient types (import.meta.env,
// asset imports, ...) — without it, `import.meta.env.DEV` in main.ts has
// no type and `tsc` rejects the scaffold's own output.
const scaffoldViteEnvDTS = `/// <reference types="vite/client" />
`

// ScaffoldVite writes a minimal Vite + TypeScript project to dir — no UI
// framework opinion, just enough to run `npm install && npm run build` and
// get an installable app directory out of it. It returns an error if dir
// already exists and is not empty — ScaffoldVite never overwrites.
//
// Unlike Scaffold, the result is not installable as-is: patchcord-app.yaml
// lives under public/ so Vite's build copies it into dist/ alongside the
// bundled JS, matching the reference dashboard example
// (apps/examples/dashboard). Build first, then point app/bundle commands
// at dir's dist subdirectory:
//
//	cd dir && npm install && npm run build
//	patchcord app install dir/dist
func ScaffoldVite(dir, id, version string) error {
	if err := ensureEmptyDir(dir); err != nil {
		return err
	}

	files := map[string]string{
		"package.json":               fmt.Sprintf(scaffoldVitePackageJSON, id, version),
		"vite.config.ts":             scaffoldViteConfig,
		"tsconfig.json":              scaffoldViteTSConfig,
		"index.html":                 fmt.Sprintf(scaffoldViteIndexHTML, id),
		".gitignore":                 scaffoldViteGitignore,
		"src/main.ts":                fmt.Sprintf(scaffoldViteMainTS, id),
		"src/vite-env.d.ts":          scaffoldViteEnvDTS,
		"public/" + ManifestFileName: fmt.Sprintf(scaffoldViteManifestTemplate, id, version),
	}

	for relPath, content := range files {
		fullPath := filepath.Join(dir, filepath.FromSlash(relPath))
		if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
			return fmt.Errorf("create %q: %w", filepath.Dir(fullPath), err)
		}
		if err := os.WriteFile(fullPath, []byte(content), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", relPath, err)
		}
	}

	return nil
}

// ensureEmptyDir creates dir if it doesn't exist yet, or errors if it
// exists and already has entries — a scaffold command must never silently
// overwrite a directory the caller has already put work into.
func ensureEmptyDir(dir string) error {
	entries, err := os.ReadDir(dir)
	if err == nil {
		if len(entries) > 0 {
			return fmt.Errorf("%q already exists and is not empty", dir)
		}
		return nil
	}
	if !os.IsNotExist(err) {
		return fmt.Errorf("check %q: %w", dir, err)
	}

	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create %q: %w", dir, err)
	}
	return nil
}
